### ISSUE TITLE
Link fault model to FaultTriggerController

### ISSUE THREAD

**Issue by TL141** [DLR-SR/FaultTriggering#23]
Having a link on the FaultTriggerContorller Interface that leads to the faulty model within the Wrapper would be nice. This avoids searching and clicking around to find the faulty model that could be a few layers down in the wrapper.

The link (or all links) could be on the documentation side of the FaultTriggerController listet in a table. If possible, the table shows which source block (e.g. Boolean Step) controls which fault. (1. column: name of the source block, 2. column: link to the fault)

Another possibility is to create a link on the Diagram interface where you see the source blocks. Just as the path of the bus connecting is showed, a direct link to the fault would be the most fast way.

**Comment by fvanderlinden** [comment]
This should be done now with #45. I think it is quite neat!
