### ISSUE TITLE
Error for createFaultPackage: "Failed to open or read ~FMUOutput\modelDescription.xml"

### ISSUE THREAD

**Issue by jak3mek** [DLR-SR/FaultTriggering#30]
Hello,
I am haveing issues regarding the following package configuration:
FaultTriggering - Version 0.6.2
Dymola  - Version 2015 DF01
Modelica - Version 3.2.1
ModelManagement - Version 1.1.3

All models (even the example "actuator") that I used to execute the createFaultPackage function led to an error: "Error: Failed to open or read ~FMUOutput\modelDescription.xml"
Did anyone else fight the same problem? Any solutions or hints?

Cheers
Jakob

**Comment by jak3mek** [comment]
The problem can be solved by

**Comment by fvanderlinden** [comment]
Should be fixed with #31  & #32 . Can you please try it on a linux machine and tell me it it worked?

Thank you for submitting the bug!

**Comment by fvanderlinden** [comment]
I assume it is fixed since no further negative feedback is given
