### ISSUE TITLE
Several minor issues with latest release version

### ISSUE THREAD

**Issue by hubertus65** [DLR-SR/FaultTriggering#54]
Hi, 

I found 3 minor issues when using the latest released FaultTriggereing Library: 

- a GUI choice misspelled true as 3, giving clear errors on PedanticCheck
- a reference to Modelica_Noise that should be Modelica.Blocks.Noise instead
- a missing uses annotation for AdvancedNoise, as well as missing instructions that it is needed as well. 
the only remaining error in Dymola 2018 pedantic check after that is a reference to '__Dymola_interactive'  in an annotation. 

I have not done any more detailed checking, but all of the above is easy to fix.

**Comment by fvanderlinden** [comment]
Dear Hubertus,

Thank you for mentioning the bugs. At the Moment I have not enough time to go through, but if you send me a pull request, I am sure that I can find the time to integrate it.

Thank you, Frans

**Comment by tbeu** [comment]
Resolved by e1405ed4d32574b19e9587638bc9ec82e2045c39, b9a5cd8cdef0d05894ca769c28964eda71d33d7b and 536ff859bce69b5c9d5244e9b0f2cf4b66331f12.

**Comment by tbeu** [comment]
I believe this can be closed.

**Comment by tbeu** [comment]
Issues are resolved.

**Comment by fvanderlinden** [comment]
Thanks!
