### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by tbeu** [DLR-SR/FaultTriggering#64]
Since the `release` branch is set as default branch and some contributers address their pull requests w.r.t. the `release` branch and others w.r.t. the `master` branch it is hard to tell which branch is the preferred branch for contributions.

**Comment by fvanderlinden** [comment]
It would be best to commit only to the master branch, and use the release branch for releases.

**Comment by tbeu** [comment]
It would be extremely helpful then to switch the default branch from release to master. Thanks.
