### ISSUE TITLE
Inconsistent automatic inner faultTrigger / Unable to CreatePackage from PreExisting Actuator model

### ISSUE THREAD

**Issue by Techno-Anarchist** [DLR-SR/FaultTriggering#77]
i am unable to run the Actuator Model through the createFaultPackage 
resulting in Error:
Note: No "faultTrigger" component is defined. A default faultTrigger component will be used.
Inconsistent automatic inner faultTrigger.
Component context: faultTrigger
Component declared as FaultTrigger faultTrigger in [FaultTriggering.FaultOutput](modelica://FaultTriggering.FaultOutput)
File: ...FaultTriggering-0.6.6/FaultTriggering/FaultOutput/Internal/InternalBooleanFault.mo, line 5
Component context: motor.ktFault.faultTrigger
Component declared as FaultTrigger faultTrigger in [FaultTriggering.FaultOutput](modelica://FaultTriggering.FaultOutput)
File: ...FaultTriggering-0.6.6/FaultTriggering/FaultOutput/Internal/InternalIntegerFault.mo, line 5

ERRORS have been issued.

Also same error when Checking model aswell as Checking or running createFaultPackage on a new device with Faults added.

**Comment by AndreasPfeiffer** [comment]
Please could you specify in more detail, how we can reproduce the issue? Which Dymola version and which version of the Modelica Standard Library do you use? Is your platform Windows? What do you exactly do before the issue appears?

**Comment by Techno-Anarchist** [comment]
Thanks, I am using Windows 10, Modelica Standard Library Version 4.0.0. Dymola 2022 (64-bit)
and in the simplest example I go to Actuator Model and click Check

**Comment by AndreasPfeiffer** [comment]
The library FaultTriggering is not compatible with Modelica Standard Library 4.0.0. That is the reason for the issue in your first post. Because in the library there are functions generating Modelica code, a conversion seems to be more complex than just applying a conversion script. Currently, there is no plan to update the library.

**Comment by Techno-Anarchist** [comment]
Ahhh, is there anywhere you can point me to the difficulties and changes required if I were to update the library?
